

package LC.PrenotationApp.Controller;

import LC.PrenotationApp.BuisnessLogic.GestorePrenotazioni;
import LC.PrenotationApp.BuisnessLogic.GestoreRecensioni;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

//@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ControllerUtente {
    // Which is auto-generated by Spring, we will use it to handle the data
    private GestorePrenotazioni gestorePrenotazioni;
    private GestoreRecensioni gestoreRecensioni;

    //front end code


}
