package LC.PrenotationApp.Controller;

import LC.PrenotationApp.Entities.Utente;
import LC.PrenotationApp.DAO.UtentiDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;

@Controller // This means that this class is a Controller
@RequestMapping(path="/login") // This means URL's start with /demo (after Application path)
public class LoginController {
    @Autowired
    private UtentiDao utentiDao;// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
//    @PostMapping(path="/add") // Map ONLY POST Requests
//    public @ResponseBody String addNewUser (@RequestParam String username, @RequestParam String password) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//        Utente n = new Utente(username, password, "cscs.mail");
//        utentiDao.save(n);
//        return "Saved";
//    }
    @GetMapping(path="/add")
    public String loginForm(Model model) {
        model.addAttribute("login_ingo", new Utente());
        return "login";
    }
    @PostMapping(path="/add")
    public String loginSubmit(@ModelAttribute Utente utente, Model model) {
        model.addAttribute("login_info", utente);
        return "submit";
    }
}
