

package LC.PrenotationApp.Controller;

import LC.PrenotationApp.BuisnessLogic.GestorePrenotabili;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ControllerManager {
    // Which is auto-generated by Spring, we will use it to handle the data
    private GestorePrenotabili gestorePrenotabili;

    //front end code


}
