package LC.PrenotationApp.Controller;

import LC.PrenotationApp.DAO.UtentiDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

@Controller // This means that this class is a Controller
@RequestMapping(path="/login") // This means URL's start with /demo (after Application path)
public class LoginController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UtentiDao utentiDao;

    public LoginController () throws ClassNotFoundException, SQLException {
        Class.forName("org.mariadb.jdbc.Driver");
        System.out.println("Driver Loaded");


    }

    public String loginForm() {
        return "hello";
    }


}
