

package LC.PrenotationApp.Controller;

import LC.PrenotationApp.BuisnessLogic.ItemManager;

//@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ManagerController {
    // Which is auto-generated by Spring, we will use it to handle the data
    private ItemManager itemManager;

    //front end code


}
