

package LC.PrenotationApp.Controller;

import LC.PrenotationApp.BuisnessLogic.PrenotationConfirm;
import LC.PrenotationApp.BuisnessLogic.PrenotationManager;

//@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class StaffController {
    // Which is auto-generated by Spring, we will use it to handle the data
    private PrenotationManager prenotationManager;
    private PrenotationConfirm prenotationConfirm;

    //front end code


}
