

package LC.PrenotationApp.Controller;

import LC.PrenotationApp.BuisnessLogic.ReservationConfirm;
import LC.PrenotationApp.BuisnessLogic.ReservationManager;

//@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class StaffController {
    // Which is auto-generated by Spring, we will use it to handle the data
    private ReservationManager reservationManager;
    private ReservationConfirm reservationConfirm;

    //front end code


}
