

package LC.PrenotationApp.Controller;

import LC.PrenotationApp.BuisnessLogic.GestorePrenotazioni;
import LC.PrenotationApp.BuisnessLogic.GestoreRecensioni;

//@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class UserController {
    // Which is auto-generated by Spring, we will use it to handle the data
    private GestorePrenotazioni gestorePrenotazioni;
    private GestoreRecensioni gestoreRecensioni;

    //front end code
}
