package LC.PrenotationApp;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ConfermaPrenotazioni {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PrenotazioniDao prenotazioniDao;
    @Autowired // This means to get the bean called userRepository
    private PrenotabiliDao prenotabiliDao;

}